development: &development
  adapter: mysql2
  host: <%= Settings.databases.host %>  
  database: <%= Settings.databases.database %>
  username: <%= Settings.databases.username %>
  password: <%= Settings.databases.password %>
  encoding: utf8
  
staging:
  <<: *development

production:  
  <<: *development
  
test:
  <<: *development

