development: &development
  adapter: mysql2
  username: <%= (ENV['UMBRA_DB_USER'] || "root") %>
  host: <%= (ENV['UMBRA_DB_HOST'] || "localhost") %>
  port: <%= (ENV['UMBRA_DB_PORT'] || "") %>
  database: <%= (ENV['UMBRA_DB_DATABASE'] || "umbra_test") %>
  password: <%= ENV['UMBRA_DB_PASSWORD'] %>
  encoding: utf8

staging:
  <<: *development

production:
  <<: *development

test:
  <<: *development
