development: &development
  adapter: mysql2
  host: <%= Settings.databases.host %>  
  database: <%= Settings.databases.database %>
  username: <%= Settings.databases.username %>
  password: <%= Settings.databases.password %>
  encoding: utf8

test:
  <<: *development
  host: <%= Settings.databases.host %>
  database: <%= Settings.databases.database %>
  username: <%= Settings.databases.username %>

staging:
  <<: *development
  host: <%= Settings.databases.host %>

production:  
  <<: *development
  host: <%= Settings.databases.host %>

travis:
  adapter: mysql2
  database: nyu_umbra_test
  username: root
  encoding: utf8
