# Default public settings
  
databases: 
  password: 
  username: root
  database: nyu_umbra_test
  host: localhost

sunspot:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING

login:
  default_admins: ["real_user"]
  pds_url: 
  calling_system: 

solr: 
  url: "http://127.0.0.1:8981/solr"
  
# A dummy secret token for dev sessions and public consumption 

secret_token: '9f35d644c9e64245a7c54bf3d738a4159b79cccf684c2fdedfdfc4dfdadbfd3bd20ed38e72e5013001fdea7d438ea92310a686fe51b835c19d6ea785056695d0'
