development: &development
  solr:
    hostname: <%= Settings.sunspot.solr.hostname %>
    path: <%= Settings.sunspot.solr.path %>
    port: <%= Settings.sunspot.solr.port %>
    log_level: <%= Settings.sunspot.solr.log_level %>

staging:
  <<: *development

production:
  <<: *development

test:
  <<: *development
